"""empty message

Revision ID: 167fe864cff6
Revises: 289ee1d93177
Create Date: 2014-07-20 10:31:57.627525

"""

# revision identifiers, used by Alembic.
revision = '167fe864cff6'
down_revision = '289ee1d93177'

from alembic import op
import sqlalchemy as sa

new_string = sa.String(length=100)

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
     op.alter_column('title', 'title_number', type_=new_string)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
