"""empty message

Revision ID: 27a8364a2c7b
Revises: 167fe864cff6
Create Date: 2014-07-20 17:08:12.499407

"""

# revision identifiers, used by Alembic.
revision = '27a8364a2c7b'
down_revision = '167fe864cff6'

from alembic import op
import sqlalchemy as sa


new_string = sa.String(length=100)

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
     op.alter_column('title', 'house_number', type_=new_string)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
