"""empty message

Revision ID: 289ee1d93177
Revises: 3ae27f95ebf9
Create Date: 2014-07-17 11:57:26.197288

"""

# revision identifiers, used by Alembic.
revision = '289ee1d93177'
down_revision = '3ae27f95ebf9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('title', sa.Column('town', sa.String(length=100), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('title', 'town')
    ### end Alembic commands ###
