"""empty message

Revision ID: 3ae27f95ebf9
Revises: 92d260834de
Create Date: 2014-07-17 11:22:43.455534

"""

# revision identifiers, used by Alembic.
revision = '3ae27f95ebf9'
down_revision = '92d260834de'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('title', sa.Column('house_number', sa.String(length=10), nullable=True))
    op.add_column('title', sa.Column('price_paid', sa.Float(), nullable=True))
    op.add_column('title', sa.Column('road', sa.String(length=1000), nullable=True))
    op.drop_column('title', 'address')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('title', sa.Column('address', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    op.drop_column('title', 'road')
    op.drop_column('title', 'price_paid')
    op.drop_column('title', 'house_number')
    ### end Alembic commands ###
