"""empty message

Revision ID: 92d260834de
Revises: None
Create Date: 2014-07-13 13:46:53.505094

"""

# revision identifiers, used by Alembic.
revision = '92d260834de'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('title',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title_number', sa.String(length=9), nullable=True),
    sa.Column('address', sa.String(length=1000), nullable=True),
    sa.Column('post_code', sa.String(length=25), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title_number')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('title')
    ### end Alembic commands ###
